set export

publish:
    # if not logged in, run `npm adduser` beforehand
    just build-node
    cd pkg && npm publish --access=public

    just build-web
    cd pkg && npm publish --access=public

# 0. set package name
# 1. compile
# 2. add "snippets" to the 'files' array in package.json
# 3. add correct README

build-web:
    sed -i -e 's/name = "compiler-node"/name = "compiler-web"/g' ./Cargo.toml
    wasm-pack build --target=web --scope=pomsky-lang -- --features suggestions
    sed -i -e 's/"files": \[/"files": \[\n    "snippets",/g' ./pkg/package.json
    cp README-web.md pkg/README.md

build-node:
    sed -i -e 's/name = "compiler-web"/name = "compiler-node"/g' ./Cargo.toml
    wasm-pack build --scope=pomsky-lang -- --features suggestions
    sed -i -e 's/"files": \[/"files": \[\n    "snippets",/g' ./pkg/package.json
    cp README-node.md pkg/README.md
